import type { BlogArticle, BlogArticleImage } from "@/lib/blog";

export const images = {
  "flight-delay-assistance-thresholds": {
    src: "https://images.unsplash.com/photo-1530521954074-e64f6810b32d?auto=format&fit=crop&w=1600&q=82",
    alt: "Airport departures board showing delayed flights",
    position: "center",
  },
  "overnight-flight-delay-hotel-transfer-proof": {
    src: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=82",
    alt: "Passenger waiting in an airport terminal overnight",
    position: "center",
  },
  "airport-closure-flight-delay-compensation": {
    src: "https://images.unsplash.com/photo-1494412651409-8963ce7935a7?auto=format&fit=crop&w=1600&q=82",
    alt: "Aircraft waiting on a runway after an airport disruption",
    position: "center",
  },
  "deicing-flight-delay-compensation": {
    src: "https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?auto=format&fit=crop&w=1600&q=82",
    alt: "Aircraft at a gate before winter departure",
    position: "center",
  },
  "extra-costs-after-flight-delay": {
    src: "https://images.unsplash.com/photo-1529074963764-98f45c47344b?auto=format&fit=crop&w=1600&q=82",
    alt: "Passenger reviewing receipts after a disrupted flight",
    position: "center",
  },
  "rerouting-another-airline-flight-delay": {
    src: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1600&q=82",
    alt: "Aircraft at airport gates during rerouting",
    position: "center",
  },
} satisfies Record<string, BlogArticleImage>;

const commonBullets = {
  sr: [
    "Meri se posledica po krajnju destinaciju, ne samo neprijatnost na gejtu.",
    "Pravo na brigu i fiksna naknada proveravaju se odvojeno.",
    "Najbolji zahtev ima vremensku liniju, razlog kašnjenja i račune po stavkama.",
  ],
  en: [
    "Measure the consequence for the final destination, not only the gate wait.",
    "Care rights and fixed compensation are checked separately.",
    "The strongest claim has a timeline, delay reason and itemized receipts.",
  ],
};

export const articles = [
  {
    id: "flight-delay-assistance-thresholds",
    publishedAt: "2026-05-14",
    updatedAt: "2026-05-14",
    sr: {
      slug: "kasnjenje-leta-pragovi-obrok-voda",
      title: "Kašnjenje leta: kada imate pravo na obrok, vodu i pomoć",
      description: "Kako se kod kašnjenja leta proveravaju pragovi za obrok, osveženje, komunikaciju, hotel i refundaciju troškova.",
      excerpt: "Pravo na pomoć tokom čekanja ne zavisi samo od tri sata kašnjenja na dolasku. Obrok, voda i komunikacija mogu biti važni mnogo ranije.",
      category: "Pravo na brigu",
      readTime: "8 min čitanja",
      sections: [
        {
          heading: "Zašto se pomoć proverava odvojeno od naknade",
          body: [
            "Kod kašnjenja leta putnici često gledaju samo pitanje fiksne naknade. Ipak, [naknada za kašnjenje leta](/naknada-za-kasnjenje-leta) i pravo na pomoć tokom čekanja nisu isto. Naknada se najčešće proverava prema dolasku na krajnju destinaciju, ruti i razlogu kašnjenja. Pomoć se proverava prema tome koliko se očekuje da čekate u polasku i koliko je let dug.",
            "Zato putnik može imati pravo na obrok, vodu ili komunikaciju čak i kada još nije jasno da li će dolazak preći tri sata. Obrnuto, moguće je da se fiksna naknada kasnije odbije zbog vanrednih okolnosti, ali da troškovi razumnog čekanja i dalje ostanu posebna tema. Dobar zahtev zato mora odvojiti brigu, refundaciju troškova i fiksnu naknadu.",
          ],
          bullets: commonBullets.sr,
        },
        {
          heading: "Pragovi od 2, 3 i 4 sata",
          body: [
            "Za kraće letove pomoć obično postaje važna kada se očekuje čekanje od najmanje 2 sata. Za srednje rute prag je najčešće 3 sata, a za duge letove van evropskog prostora 4 sata. Ti pragovi ne znače automatsku isplatu fiksne naknade; oni govore kada aviokompanija treba da organizuje razumnu brigu dok čekate.",
            "Na rutama iz Srbije ovo je posebno praktično kod letova ka evropskim čvorištima, jer su mnoge deonice kraće ili srednje dužine. Putnik treba da pita gde se preuzimaju vaučeri, kako se obezbeđuje voda i da li postoji pisano obaveštenje o novom vremenu polaska. Ako odgovor ostane usmen, napravite screenshot statusa leta i zabeležite vreme kada ste pitali.",
          ],
        },
        {
          heading: "Hotel i transfer kada se čeka do sutra",
          body: [
            "Ako se novi polazak očekuje tek narednog dana, obrok više nije dovoljno rešenje. Tada treba tražiti hotel i transfer između aerodroma i smeštaja. Aviokompanija može sama organizovati smeštaj, dati vaučer ili u nekim situacijama ostaviti putnika da plati pa kasnije traži refundaciju.",
            "Ako sami plaćate hotel, izaberite razumnu opciju blizu aerodroma. Sačuvajte potvrdu rezervacije, račun, dokaz plaćanja i poruku iz koje se vidi da pomoć nije ponuđena ili nije bila dostupna. Bez tog traga kompanija kasnije može tvrditi da je pomoć postojala ili da trošak nije bio nužan.",
          ],
        },
        {
          heading: "Šta ako vaučer nije dovoljan",
          body: [
            "Vaučer male vrednosti ne zatvara automatski pitanje dodatnih troškova. Ako čekanje traje dugo, ako restoran ne prihvata vaučer ili ako je aerodrom noću zatvoren, napišite šta se stvarno dogodilo. Nije dovoljno samo reći da je pomoć bila loša; korisno je navesti kada je vaučer izdat, gde je mogao da se koristi i zašto nije pokrio osnovnu potrebu.",
            "Dodatni troškovi treba da budu razumni: voda, jednostavan obrok, lokalni transfer i osnovni smeštaj mnogo su lakši za odbranu od luksuznih računa. Let Kasni u takvim slučajevima prvo slaže hronologiju i račune, pa tek onda odvaja šta je zahtev za troškove, a šta zahtev za fiksnu naknadu.",
          ],
        },
        {
          heading: "Kako pripremiti zahtev za troškove čekanja",
          body: [
            "U zahtevu navedite broj leta, rutu, planirano vreme polaska, novo vreme polaska, koliko ste čekali i šta je aviokompanija ponudila. Zatim odvojeno navedite račune za obrok, vodu, hotel, transfer ili komunikaciju. Svaki trošak treba imati kratak razlog i dokaz da je nastao tokom čekanja.",
            "Ako je dolazak na krajnju destinaciju kasnio tri sata ili više, dodajte poseban pasus za proveru fiksne naknade. Takva struktura sprečava da aviokompanija odgovori samo na jedan deo i ignoriše ostatak. Uredan dosije je posebno važan kada kompanija kasnije tvrdi da je razlog kašnjenja bio van njene kontrole.",
            "Ako niste sigurni koji prag važi za vašu rutu, nemojte nagađati iz sećanja. Sačuvajte itinerer i prepustite proveru na osnovu aerodroma, udaljenosti i stvarnog vremena čekanja.",
          ],
        },
      ],
    },
    en: {
      slug: "flight-delay-assistance-thresholds",
      title: "Flight delay: when you have a right to meals, water and assistance",
      description: "How assistance thresholds work during a flight delay: meals, refreshments, communication, hotel and reimbursement of waiting costs.",
      excerpt: "Care during the wait is not only about the 3-hour arrival threshold. Meals, water and communication may matter much earlier.",
      category: "Care rights",
      readTime: "8 min read",
      sections: [
        {
          heading: "Why assistance is checked separately from compensation",
          body: [
            "During a flight delay, passengers often look only at fixed compensation. But [flight delay compensation](/en/flight-delay-compensation) and care during the wait are not the same. Compensation is usually checked by final arrival time, route and delay reason. Assistance is checked by how long you are expected to wait at departure and how long the flight is.",
            "That means a passenger may have a right to meals, water or communication even before it is clear whether final arrival will be three hours late. The reverse is also possible: fixed compensation may later be refused because of extraordinary circumstances, while reasonable waiting costs remain a separate issue. A good claim separates care, cost reimbursement and fixed compensation.",
          ],
          bullets: commonBullets.en,
        },
        {
          heading: "The 2, 3 and 4-hour assistance thresholds",
          body: [
            "For shorter flights, assistance usually becomes important when the expected wait is at least 2 hours. For medium routes the threshold is commonly 3 hours, and for long flights outside the European area it is 4 hours. These thresholds do not mean automatic fixed compensation; they indicate when the airline should organize reasonable care while you wait.",
            "For routes from Serbia, this is practical on flights to European hubs because many segments are short or medium distance. Ask where vouchers are collected, how water is provided and whether there is a written notice with the new departure time. If the answer remains verbal, take a flight-status screenshot and record when you asked.",
          ],
        },
        {
          heading: "Hotel and transfer when the wait continues tomorrow",
          body: [
            "If the new departure is expected only the next day, a meal is no longer enough. Ask for hotel accommodation and transport between the airport and hotel. The airline may arrange accommodation itself, issue a voucher or, in some situations, leave passengers to pay and request reimbursement later.",
            "If you pay for accommodation yourself, choose a reasonable option near the airport. Keep the booking confirmation, invoice, payment proof and a message showing that assistance was not offered or was unavailable. Without that trail, the airline may later argue that help existed or that the cost was unnecessary.",
          ],
        },
        {
          heading: "What if the voucher is not enough",
          body: [
            "A low-value voucher does not automatically close the issue of extra costs. If the wait is long, if a restaurant does not accept the voucher or if the airport is closed overnight, write down what actually happened. It is not enough to say the assistance was poor; state when the voucher was issued, where it could be used and why it did not cover the basic need.",
            "Additional costs should be reasonable: water, a simple meal, local transfer and basic accommodation are much easier to defend than luxury receipts. In these cases, Let Kasni first organizes the timeline and receipts, then separates the cost claim from the fixed compensation claim.",
          ],
        },
        {
          heading: "How to prepare a claim for waiting costs",
          body: [
            "In the claim, state the flight number, route, scheduled departure, new departure time, how long you waited and what the airline offered. Then list receipts for meals, water, hotel, transfer or communication separately. Each cost should have a short reason and proof that it arose during the wait.",
            "If arrival at the final destination was three hours or more late, add a separate paragraph requesting fixed compensation review. This structure prevents the airline from answering only one part and ignoring the rest. A clean file is especially important when the airline later says the delay reason was outside its control.",
          ],
        },
      ],
    },
  },
  {
    id: "overnight-flight-delay-hotel-transfer-proof",
    publishedAt: "2026-05-14",
    updatedAt: "2026-05-14",
    sr: {
      slug: "nocno-kasnjenje-leta-hotel-transfer-dokazi",
      title: "Noćno kašnjenje leta: hotel, transfer i dokazi za refundaciju",
      description: "Šta putnik treba da uradi kada kašnjenje leta pređe u noć: hotel, transfer, računi, poruke i zahtev za refundaciju troškova.",
      excerpt: "Kada se polazak pomeri za naredni dan, dokazni dosije za hotel i transfer često odlučuje da li će troškovi biti vraćeni.",
      category: "Pravo na brigu",
      readTime: "8 min čitanja",
      sections: [
        { heading: "Kada noćno čekanje menja slučaj", body: ["Noćno kašnjenje nije samo duže čekanje na gejtu. Ako se polazak pomera za sledeći dan, putnik treba da traži smeštaj, prevoz do hotela i nazad, obrok i jasnu informaciju o novom planu. To se proverava odvojeno od [naknade za kašnjenje leta](/naknada-za-kasnjenje-leta), ali može stajati u istom dosijeu.", "Najveći problem nastaje kada osoblje kaže da hotela nema, da se čeka poruka ili da putnici sami nađu smeštaj. Tada treba brzo napraviti pisani trag. Pošaljite kratku poruku aviokompaniji ili sačuvajte screenshot aplikacije pre nego što platite hotel, jer kasniji zahtev mora pokazati zašto ste morali sami da reagujete."], bullets: commonBullets.sr },
        { heading: "Prvo tražite rešenje od aviokompanije", body: ["Najbolje je prvo pitati aviokompaniju za hotel i transfer. Ako postoji šalter, tražite vaučer ili pisanu potvrdu. Ako komunikacija ide kroz aplikaciju, sačuvajte poruke. Ako osoblje daje samo usmeno objašnjenje, zapišite vreme, mesto i ime ili funkciju osobe sa kojom ste razgovarali.", "Ovo nije formalnost. Kada kasnije tražite refundaciju, kompanija često pita zašto niste koristili ponuđeni smeštaj. Ako ponuđenog smeštaja nije bilo, dokaz mora pokazati da ste pitali, čekali razumno vreme i izabrali nužnu opciju za noć."] },
        { heading: "Koji hotel i transfer su razumni", body: ["Razuman hotel je obično smeštaj koji je dostupan iste noći, blizu aerodroma i odgovara osnovnoj potrebi da se prespava do novog leta. Ako putujete sa decom, starijom osobom ili imate zdravstveni razlog, napišite to jer može objasniti zašto je određena opcija bila nužna.", "Za transfer čuvajte račun taksija, kartičnu potvrdu ili potvrdu prevoznika. Ako hotel nudi shuttle, ali ga nije bilo u potrebnom terminu, zabeležite to. U zahtevu treba povezati transfer sa hotelom i novim vremenom polaska."] },
        { heading: "Dokazi koje treba sačuvati te noći", body: ["Sačuvajte boarding pass, potvrdu rezervacije, obaveštenje o novom letu, dokaz da je polazak pomeren za sutra, račun hotela, dokaz plaćanja, račun transfera i poruke aviokompanije. Ako je hotel rezervisan online, sačuvajte i email potvrdu sa datumom i cenom.", "Korisno je napraviti kratku hronologiju: kada je najavljeno kašnjenje, kada ste pitali za hotel, šta je odgovoreno, kada ste platili smeštaj i kada ste se vratili na aerodrom. Takva vremenska linija često vredi više od dugog objašnjenja posle putovanja."] },
        { heading: "Kako spojiti troškove sa zahtevom za naknadu", body: ["U istom obraćanju možete tražiti refundaciju hotela i transfera, a odvojeno proveru fiksne naknade ako je dolazak na krajnju destinaciju kasnio najmanje tri sata. Ne mešajte ova dva osnova u jednu rečenicu jer kompanija tada lako odgovori samo na jednostavniji deo.", "Let Kasni kod noćnih kašnjenja prvo proverava rutu, dolazak i razlog kašnjenja, a zatim posebno obrađuje troškove brige. Taj redosled je važan jer putnik može imati refundaciju razumnog hotela čak i kada se fiksna naknada kasnije spori.", "Posebno je važno da se ne šalje samo račun hotela bez konteksta. Dodajte planirani i stvarni polazak, vreme kada je postalo jasno da se leti sutra, dokaz da ste tražili pomoć i objašnjenje zašto je izabrani smeštaj bio razuman. Ako je kašnjenje nastalo na povratku u Srbiju, navedite i kako ste se vratili kući posle kasnog dolaska, jer transfer posle hotela i transfer posle sletanja nisu ista stavka."] },
        { heading: "Kada je potrebna profesionalna provera", body: ["Profesionalna provera je najkorisnija kada aviokompanija ne spori samo račun, već celu okolnost kašnjenja. Tada se u jednom dosijeu spajaju hotel, transfer, krajnji dolazak, razlog kašnjenja i pitanje da li je ponuđena razumna alternativa.", "Ako putnik šalje sve odvojeno, kompanija može refundirati mali deo troška i prećutati veće pitanje naknade. Zato se prvo pravi redosled događaja, zatim tabela troškova, pa tek onda zahtev koji jasno traži odgovor na svaku stavku."] },
      ],
    },
    en: {
      slug: "overnight-flight-delay-hotel-transfer-proof",
      title: "Overnight flight delay: hotel, transfer and proof for reimbursement",
      description: "What passengers should do when a flight delay turns into an overnight wait: hotel, transfer, receipts, messages and reimbursement request.",
      excerpt: "When departure moves to the next day, the evidence file for hotel and transfer often decides whether costs are reimbursed.",
      category: "Care rights",
      readTime: "8 min read",
      sections: [
        { heading: "When an overnight wait changes the case", body: ["An overnight delay is not only a longer gate wait. If departure moves to the next day, passengers should ask for accommodation, transport to and from the hotel, a meal and clear information about the new plan. This is checked separately from [flight delay compensation](/en/flight-delay-compensation), but it can sit in the same case file.", "The biggest problem comes when staff say no hotel is available, passengers should wait for a message or they should find accommodation themselves. At that point, create a written trail quickly. Send a short message to the airline or save an app screenshot before paying for a hotel, because the later claim must show why you had to act yourself."], bullets: commonBullets.en },
        { heading: "Ask the airline for a solution first", body: ["The best first step is to ask the airline for hotel accommodation and transfer. If there is a desk, request a voucher or written confirmation. If communication happens through the app, keep the messages. If staff give only a verbal explanation, write down the time, place and name or role of the person you spoke with.", "This is not paperwork for its own sake. When you later request reimbursement, the airline may ask why you did not use the accommodation it offered. If no accommodation was offered, the evidence should show that you asked, waited a reasonable time and chose a necessary overnight option."] },
        { heading: "Which hotel and transfer are reasonable", body: ["A reasonable hotel is usually accommodation available that night, near the airport and suitable for the basic need to sleep before the new flight. If you travel with children, an older passenger or have a health reason, write that down because it may explain why a particular option was necessary.", "For transfer, keep the taxi receipt, card confirmation or transport receipt. If the hotel has a shuttle but it was not available at the required time, record that. In the claim, connect the transfer to the hotel and new departure time."] },
        { heading: "Evidence to save that night", body: ["Keep the boarding pass, booking confirmation, notice of the new flight, proof that departure moved to tomorrow, hotel invoice, payment proof, transfer receipt and airline messages. If the hotel was booked online, keep the confirmation email showing date and price.", "It helps to create a short timeline: when the delay was announced, when you asked for hotel accommodation, what was answered, when you paid for accommodation and when you returned to the airport. This timeline is often more useful than a long explanation after the journey."] },
        { heading: "How to combine costs with the compensation claim", body: ["In the same message, you can request reimbursement for hotel and transfer, and separately ask for fixed compensation review if arrival at the final destination was at least three hours late. Do not mix these grounds into one sentence because the airline can then answer only the easier part.", "For overnight delays, Let Kasni first checks route, arrival and delay reason, then separately handles care expenses. That order matters because a passenger may have reimbursement for a reasonable hotel even when fixed compensation is later disputed.", "Do not send only the hotel invoice without context. Add scheduled and actual departure, the time when it became clear that travel moved to tomorrow, proof that you asked for assistance and a short explanation of why the accommodation was reasonable. If the delay happened on the return to Serbia, also separate hotel transfer from the later journey home after landing."] },
        { heading: "When professional review is useful", body: ["Professional review is most useful when the airline disputes not only the receipt, but the whole delay situation. The same file then connects hotel, transfer, final arrival, delay reason and whether a reasonable alternative was offered.", "If passengers send everything separately, the airline may reimburse a small cost and stay silent on the larger compensation question. The safer order is event timeline, cost table and then a claim that asks for an answer on every item."] },
      ],
    },
  },
  {
    id: "airport-closure-flight-delay-compensation",
    publishedAt: "2026-05-14",
    updatedAt: "2026-05-14",
    sr: { slug: "zatvoren-aerodrom-kasnjenje-leta-naknada", title: "Zatvoren aerodrom i kašnjenje leta: kada naknada ipak vredi proveriti", description: "Kako proveriti kašnjenje kada je aerodrom bio zatvoren zbog vremena, piste, bezbednosti ili kontrole letenja.", excerpt: "Zatvaranje aerodroma često jeste jak argument aviokompanije, ali ne objašnjava automatski svaki sat kašnjenja niti briše pravo na brigu.", category: "Vanredne okolnosti", readTime: "8 min čitanja", sections: [
      { heading: "Zašto zatvoren aerodrom nije kraj provere", body: ["Kada aviokompanija kaže da je aerodrom bio zatvoren, putnik često pretpostavi da nema nikakva prava. To nije tačno. Zatvaranje aerodroma može biti vanredna okolnost za fiksnu [naknadu za kašnjenje leta](/naknada-za-kasnjenje-leta), ali i dalje treba proveriti gde je zatvaranje nastalo, koliko je trajalo i da li objašnjava baš vaš kasni dolazak.", "Pravo na brigu tokom čekanja obično ostaje posebno pitanje. Čak i kada kompanija nije kriva za zatvaranje piste ili aerodroma, putnici mogu imati pravo na obrok, vodu, komunikaciju, hotel i transfer ako čekanje traje dovoljno dugo."], bullets: commonBullets.sr },
      { heading: "Koji tip zatvaranja je naveden", body: ["Nije isto da li je aerodrom zatvoren zbog magle, snega, zaleđene piste, bezbednosnog incidenta, rada kontrole letenja ili infrastrukturnog kvara. Svaki razlog traži drugačiji dokaz.", "Ako je zatvoren polazni aerodrom, posledica je obično jasnija. Ako je problem bio na prethodnom aerodromu u rotaciji aviona ili na destinaciji, treba proveriti vremensku liniju."] },
      { heading: "Vremenska linija posle ponovnog otvaranja", body: ["Najvažnije pitanje često nije samo kada je aerodrom bio zatvoren, već šta se desilo posle ponovnog otvaranja. Ako su drugi letovi krenuli, a vaš je dodatno čekao zbog aviona, posade ili operativne reorganizacije, slučaj ne treba zatvarati bez detaljnije provere.", "Zapišite vreme zatvaranja ako je objavljeno, vreme nove najave, vreme ukrcavanja, vreme poletanja i stvarni dolazak. Takva hronologija može pokazati da je jedan deo kašnjenja bio van kontrole, a drugi deo možda nije."] },
      { heading: "Briga tokom čekanja i noćenja", body: ["Ako zatvaranje aerodroma znači višesatno čekanje, pitajte za obrok, vodu i komunikaciju. Ako se polazak pomera za sutra, pitajte za hotel i transfer. Nemojte pretpostaviti da vanredna okolnost znači da sve plaćate sami.", "Ako pomoć ne dobijete, kupujte razumno i čuvajte račune. U zahtevu jasno napišite da tražite refundaciju troškova brige, a ne samo fiksnu naknadu."] },
      { heading: "Kako tražiti objašnjenje od aviokompanije", body: ["Kada šaljete zahtev, tražite da kompanija navede tačan razlog zatvaranja, vremenski period, aerodrom na koji se razlog odnosio i zašto je taj događaj prouzrokovao baš vaš kasni dolazak.", "Let Kasni ovakve slučajeve proverava kroz rutu, let u rotaciji, raspoložive poruke i račune. Cilj nije ignorisati vanredne okolnosti, nego odvojiti ono što je zaista bilo van kontrole od onoga što kompanija mora posebno da objasni ili refundira.", "Ako je zatvaranje trajalo kratko, a vaš let je krenuo mnogo kasnije, tražite objašnjenje za taj dodatni period. Ako je aerodrom bio zatvoren celu noć, fokus se često pomera sa fiksne naknade na brigu, hotel, transfer i dokaz da je kompanija organizovala razumno preusmeravanje. U oba slučaja uredna pitanja sprečavaju da dobijete samo jednu opštu rečenicu."] },
      { heading: "Kada slučaj i dalje ima vrednost", body: ["Slučaj i dalje ima vrednost kada postoje računi, noćenje, propuštena konekcija pod jednom rezervacijom ili velika razlika između vremena otvaranja aerodroma i stvarnog polaska vašeg leta.", "Tada se ne tvrdi unapred da aviokompanija sigurno duguje fiksnu naknadu. Traži se precizan odgovor, razdvajaju se troškovi brige i proverava da li je kasniji deo kašnjenja nastao zbog organizacije prevoznika. Ako imate fotografiju table polazaka ili poruku aerodroma, dodajte je uz zahtev jer pomaže da se vreme zatvaranja uporedi sa vremenom vašeg leta. Sačuvajte i boarding pass, jer bez njega često nije jasno da li ste bili spremni za putovanje.", "Ako je odgovor aviokompanije kratak, ne šaljite emotivnu žalbu. Pošaljite dopunu sa tri pitanja: kada je aerodrom bio zatvoren, kada je ograničenje prestalo i koji dokaz pokazuje da posle toga nije bilo dodatnog kašnjenja iz organizacionih razloga."] },
    ] },
    en: { slug: "airport-closure-flight-delay-compensation", title: "Airport closure and flight delay: when compensation is still worth checking", description: "How to check a delay when the airport was closed because of weather, runway conditions, security or air traffic control.", excerpt: "Airport closure is often a strong airline argument, but it does not automatically explain every hour of delay or remove care rights.", category: "Extraordinary circumstances", readTime: "8 min read", sections: [
      { heading: "Why airport closure is not the end of the review", body: ["When an airline says the airport was closed, passengers often assume they have no rights at all. That is not correct. Airport closure may be an extraordinary circumstance for fixed [flight delay compensation](/en/flight-delay-compensation), but you still need to check where the closure happened, how long it lasted and whether it explains your specific late arrival.", "Care during the wait usually remains a separate issue. Even when the airline was not responsible for a runway or airport closure, passengers may have rights to meals, water, communication, hotel and transfer if the wait is long enough."], bullets: commonBullets.en },
      { heading: "Which type of closure was stated", body: ["It matters whether the airport was closed because of fog, snow, icy runway conditions, a security incident, air traffic control or infrastructure failure. Each reason needs different evidence.", "If the departure airport was closed, the consequence is usually clearer. If the issue was at the previous airport in the aircraft rotation or at the destination, the timeline should be checked."] },
      { heading: "Timeline after the airport reopens", body: ["The key question is often not only when the airport was closed, but what happened after reopening. If other flights departed while yours waited longer because of aircraft, crew or operational reorganization, the case should not be closed without a deeper review.", "Record the closure time if published, the new notice time, boarding time, departure time and actual arrival. This timeline may show that one part of the delay was outside airline control while another part may need a separate explanation."] },
      { heading: "Care during waiting and overnight disruption", body: ["If airport closure causes several hours of waiting, ask for meals, water and communication. If departure moves to tomorrow, ask for hotel accommodation and transfer. Do not assume that an extraordinary circumstance means you must pay for everything yourself.", "If assistance is not provided, spend reasonably and keep receipts. In the claim, state clearly that you request reimbursement of care costs, not only fixed compensation."] },
      { heading: "How to request an explanation from the airline", body: ["When sending the claim, ask the airline to state the exact closure reason, time period, airport affected and why that event caused your specific late arrival.", "Let Kasni reviews these cases through route, aircraft rotation, available messages and receipts. The goal is not to ignore extraordinary circumstances, but to separate what was genuinely outside control from what the airline still has to explain or reimburse.", "If the closure lasted only briefly but your flight departed much later, ask for the reason for that additional period. If the airport was closed overnight, the focus often moves from fixed compensation to care, hotel, transfer and proof that the airline organized reasonable rerouting. In both situations, structured questions prevent a one-line generic answer."] },
      { heading: "When the case still has value", body: ["The case still has value when there are receipts, an overnight stay, a missed connection under one booking or a large gap between airport reopening and actual departure of your flight.", "That does not mean claiming fixed compensation blindly. It means requesting a precise answer, separating care costs and checking whether the later part of the delay came from carrier organization."] },
    ] },
  },
  {
    id: "deicing-flight-delay-compensation",
    publishedAt: "2026-05-14",
    updatedAt: "2026-05-14",
    sr: { slug: "odledjivanje-aviona-kasnjenje-leta-naknada", title: "Odleđivanje aviona i kašnjenje leta: kada postoji osnov za naknadu", description: "Kako proveriti kašnjenje zbog odleđivanja aviona, snega, leda, nedostatka opreme ili zimskog operativnog plana.", excerpt: "Sneg i led mogu biti vanredna okolnost, ali kod odleđivanja treba proveriti da li je problem bio vreme ili organizacija aviokompanije.", category: "Razlozi kašnjenja", readTime: "8 min čitanja", sections: [
      { heading: "Zašto odleđivanje nije uvek isti razlog", body: ["Odleđivanje aviona je normalan deo zimskog letenja. Kada je vreme ekstremno, pista zatvorena ili aerodrom ograničen, aviokompanija može imati jak argument protiv fiksne [naknade za kašnjenje leta](/naknada-za-kasnjenje-leta). Ali ako je kašnjenje nastalo zato što nije bilo opreme, tečnosti, posade ili plana za očekivane zimske uslove, slučaj vredi proveriti pažljivije.", "Putnik ne mora dokazivati interne propuste kompanije, ali treba sačuvati činjenice koje otvaraju pitanje. Važno je znati da li su kasnili svi letovi, samo određena kompanija, samo jedan avion ili cela rotacija."], bullets: commonBullets.sr },
      { heading: "Šta pitati na aerodromu", body: ["Ako osoblje navodi odleđivanje, pitajte da li je problem red za odleđivanje, zatvorena pista, nedostatak opreme ili kasni dolazak aviona. Zapišite tačnu formulaciju i vreme.", "Nemojte se oslanjati samo na komentare drugih putnika. Korisniji su screenshot aplikacije, fotografija table polazaka, email aviokompanije i vreme kada je avion stvarno krenuo."] },
      { heading: "Kada zimski uslovi jačaju odbranu aviokompanije", body: ["Ako je aerodrom bio zatvoren, ako je kontrola letenja ograničila polaske ili ako je ledena kiša učinila operacije nebezbednim, fiksna naknada može biti teža. Aviokompanija ipak treba da pokaže da je taj događaj direktno pogodio konkretan let.", "Ovo je važno kod dužih rotacija. Avion može kasniti jer je prethodni aerodrom imao sneg, ali kasnije se mogu pojaviti dodatni razlozi kao posada, slot ili zamena aviona."] },
      { heading: "Briga i troškovi tokom zimskog čekanja", body: ["Zimska kašnjenja često traju dugo i brzo prelaze u noćno čekanje. Pitajte za obrok, vodu, komunikaciju, hotel i transfer čim postane jasno da se polazak značajno pomera.", "Ako sami plaćate hranu, taksi ili hotel, birajte razumno i sačuvajte račune. Kod zimskih poremećaja korisno je zabeležiti i zašto ste morali brzo da rezervišete smeštaj."] },
      { heading: "Kako složiti zahtev posle odleđivanja", body: ["U zahtevu napišite rutu, planirani i stvarni dolazak, razlog koji je naveden, vreme čekanja na odleđivanje i sve promene obaveštenja. Ako je dolazak kasnio tri sata ili više, tražite proveru fiksne naknade.", "Let Kasni kod ovakvih slučajeva proverava da li je odleđivanje zaista bilo jedini uzrok ili samo početak problema. To je razlika između slabog zahteva i dosijea koji postavlja prava pitanja aviokompaniji.", "Dodajte i poređenje sa drugim obaveštenjima koja ste dobili tokom dana. Ako je prvo pisalo sneg, zatim tehnički pregled, pa čekanje posade, te promene ne dokazuju automatski pravo na isplatu, ali pokazuju zašto odgovor aviokompanije treba proveriti. Kod zimskih polazaka iz regionalnih aerodroma posebno je važno odvojiti ograničenje aerodroma od odluka prevoznika posle prestanka ograničenja."] },
      { heading: "Šta ne treba preskočiti", body: ["Ne treba preskočiti dokaz stvarnog dolaska, jer zimsko čekanje u polasku samo po sebi ne rešava prag od tri sata. Takođe ne treba preskočiti troškove brige, jer obrok, hotel i transfer mogu biti relevantni i kada je vremenski razlog jak.", "Najbolje je poslati zahtev koji prvo traži proveru osnova, zatim navodi troškove, a zatim pita koji dokaz potvrđuje da je ceo period kašnjenja bio posledica zimskih uslova. Ako je kompanija istog dana obavljala druge zimske polaske bez sličnog čekanja, i to vredi pomenuti kao razlog za detaljnije objašnjenje. Ne tvrdite da poređenje samo po sebi dokazuje odgovornost, već ga koristite kao signal da odgovor ne sme ostati generički.", "Ako putnik ima konekciju, odleđivanje prvog segmenta treba povezati sa dolaskom na poslednju destinaciju. Bez originalnog i novog itinerera aviokompanija može posmatrati samo prvi let, iako je pravi problem nastao tek kada je izgubljen nastavak puta."] },
    ] },
    en: { slug: "deicing-flight-delay-compensation", title: "Aircraft de-icing and flight delay: when compensation may still apply", description: "How to check a delay caused by aircraft de-icing, snow, ice, missing equipment or winter operations planning.", excerpt: "Snow and ice can be extraordinary, but with de-icing you should check whether the issue was weather or airline organization.", category: "Delay reasons", readTime: "8 min read", sections: [
      { heading: "Why de-icing is not always the same reason", body: ["Aircraft de-icing is a normal part of winter flying. When weather is extreme, a runway is closed or airport capacity is restricted, the airline may have a strong argument against fixed [flight delay compensation](/en/flight-delay-compensation). But if the delay happened because equipment, fluid, crew or planning for expected winter conditions was missing, the case is worth checking more carefully.", "Passengers do not have to prove internal airline failures, but they should save facts that raise the question. It matters whether all flights were delayed, only one airline, only one aircraft or the entire rotation."], bullets: commonBullets.en },
      { heading: "What to ask at the airport", body: ["If staff mention de-icing, ask whether the problem is the de-icing queue, runway closure, lack of equipment or late aircraft arrival. Write down the exact wording and time.", "Do not rely only on comments from other passengers. More useful evidence includes an app screenshot, departures-board photo, airline email and the time when the aircraft actually departed."] },
      { heading: "When winter conditions strengthen the airline's defence", body: ["If the airport was closed, air traffic control restricted departures or freezing rain made operations unsafe, fixed compensation can be harder. The airline should still show that the event directly affected the specific flight.", "This matters with long rotations. An aircraft may be late because the previous airport had snow, but later additional reasons may appear, such as crew, slot or aircraft replacement."] },
      { heading: "Care and costs during winter waiting", body: ["Winter delays often last long and can quickly turn into an overnight wait. Ask for meals, water, communication, hotel and transfer as soon as it is clear that departure is moving significantly.", "If you pay for food, taxi or hotel yourself, choose reasonably and keep receipts. During winter disruption it helps to record why you had to book accommodation quickly."] },
      { heading: "How to organize the claim after de-icing", body: ["In the claim, state the route, scheduled and actual arrival, reason given, time spent waiting for de-icing and all changes in notices. If arrival was three hours or more late, request fixed compensation review.", "In these cases, Let Kasni checks whether de-icing was truly the only cause or only the start of the problem. That is the difference between a weak complaint and a file that asks the airline the right questions.", "Add a comparison with other notices you received during the day. If the first message said snow, then technical inspection, then crew wait, those changes do not automatically prove compensation, but they show why the airline's answer should be checked. For winter departures from regional airports, separate airport restrictions from carrier decisions after the restriction ended."] },
      { heading: "What not to skip", body: ["Do not skip proof of actual arrival, because winter waiting at departure does not by itself solve the three-hour threshold. Also do not skip care costs, because meals, hotel and transfer may matter even when the weather reason is strong.", "The better claim first asks for eligibility review, then lists costs, then asks which evidence proves that the entire delay period was caused by winter conditions. If the same carrier operated other winter departures that day without a similar wait, mention that as a reason to request a more detailed explanation."] },
    ] },
  },
  {
    id: "extra-costs-after-flight-delay",
    publishedAt: "2026-05-14",
    updatedAt: "2026-05-14",
    sr: { slug: "dodatni-troskovi-posle-kasnjenja-leta", title: "Dodatni troškovi posle kašnjenja leta: šta realno može da se traži", description: "Kako razlikovati troškove brige, novu kartu, taksi, parking, hotel i posledične troškove posle kašnjenja leta.", excerpt: "Nisu svi troškovi posle kašnjenja jednako nadoknadivi. Najjači su oni koji su razumni, dokumentovani i direktno vezani za čekanje ili preusmeravanje.", category: "Troškovi i dokazi", readTime: "8 min čitanja", sections: [
      { heading: "Zašto troškove treba razdvojiti po osnovu", body: ["Posle dugog kašnjenja putnik često ima više računa: obrok, voda, taksi, hotel, nova karta, parking ili propuštena rezervacija. Neki troškovi pripadaju pravu na brigu, neki refundaciji ili preusmeravanju, a neki mogu biti slabiji jer su posledični i nisu direktno pokriveni pravilima za [naknadu za kašnjenje leta](/naknada-za-kasnjenje-leta).", "Zato ne treba sve staviti u jednu nejasnu sumu. Aviokompaniji treba poslati urednu tabelu: vrsta troška, iznos, datum, razlog, dokaz i veza sa kašnjenjem."], bullets: commonBullets.sr },
      { heading: "Troškovi tokom čekanja", body: ["Najjednostavniji troškovi su oni koji nastaju dok čekate: hrana, voda, komunikacija, osnovni hotel i transfer do hotela. Oni treba da budu razumni u odnosu na trajanje čekanja, vreme dana i dostupne opcije na aerodromu.", "Ako aviokompanija daje vaučer, ali on nije dovoljan, sačuvajte i vaučer i dodatne račune. Ako aerodrom nema otvorene prodavnice ili restoran ne prihvata vaučer, zabeležite to odmah."] },
      { heading: "Nova karta ili drugi prevoz", body: ["Kupovina nove karte na svoju ruku je rizičnija od obroka ili hotela. Pre toga treba tražiti preusmeravanje od aviokompanije i sačuvati dokaz da rešenje nije ponuđeno, da je bilo nerazumno kasno ili da više nije služilo svrsi putovanja.", "Ako ipak morate kupiti novi let, autobus ili voz, sačuvajte pretragu razumnih opcija, cenu, vreme polaska i razlog zašto ste izabrali baš tu opciju."] },
      { heading: "Parking, taksi i dodatni transferi", body: ["Parking i taksi mogu biti opravdani kada su direktna posledica kašnjenja, na primer kada se let vraća kasno noću, kada javni prevoz više ne radi ili kada je putnik preusmeren na drugi aerodrom. Ipak, veza mora biti jasna.", "U zahtevu napišite zašto je transfer bio neophodan, odakle dokle je vožnja bila i kako je povezana sa novim vremenom dolaska. Sam račun za taksi nije uvek dovoljan."] },
      { heading: "Kako Let Kasni priprema troškovni dosije", body: ["Prvo se proverava da li je dolazak otvorio pitanje fiksne naknade. Zatim se računi dele na brigu tokom čekanja, preusmeravanje, novu kartu i posledične troškove. Za svaku stavku se dodaje kratak dokazni komentar.", "Ovakav pristup je sporiji od slanja jedne slike svih računa, ali je mnogo jači. Putnik dobija dosije koji jasno pokazuje šta se traži, zbog čega se traži i koji dokaz stoji iza svake stavke.", "Ako je trošak nastao zbog izgubljene hotelske noći, zakasnelog dolaska na posao ili propuštenog privatnog prevoza, ne treba ga mešati sa osnovnim pravom na brigu. Takve stavke se označavaju kao dodatna šteta i proveravaju opreznije. Ponekad ih ne treba stavljati u prvi zahtev, jer mogu zamagliti jače stavke kao što su obrok, hotel, transfer ili nova karta koja je bila nužna za završetak puta."] },
      { heading: "Redosled slanja zahteva", body: ["Najbolji redosled je da se prvo prilože osnovni dokazi leta, zatim tabela računa, pa kratko objašnjenje za svaku stavku. Ako je račun na drugu osobu iz iste rezervacije, dodajte dokaz da je putnik bio deo istog putovanja.", "Kada postoji više putnika, ne treba automatski množiti svaki trošak. Neki računi važe po osobi, neki po sobi ili vožnji, pa dosije mora pokazati šta je zajednički trošak, a šta individualni zahtev. Ako je račun plaćen karticom člana porodice, dodajte kratko objašnjenje veze sa putnikom i rezervacijom. To smanjuje rizik da kompanija odbije trošak samo zato što ime na računu nije isto kao ime glavnog putnika. Ako postoji više računa istog dana, poređajte ih hronološki, jer se tako lakše vidi da su nastali tokom čekanja, a ne pre poremećaja."] },
    ] },
    en: { slug: "extra-costs-after-flight-delay", title: "Extra costs after a flight delay: what can realistically be claimed", description: "How to separate care costs, a new ticket, taxi, parking, hotel and consequential costs after a flight delay.", excerpt: "Not every cost after a delay is equally recoverable. The strongest costs are reasonable, documented and directly linked to waiting or rerouting.", category: "Costs and evidence", readTime: "8 min read", sections: [
      { heading: "Why costs should be separated by legal basis", body: ["After a long delay, passengers often have several receipts: meal, water, taxi, hotel, new ticket, parking or a missed booking. Some costs belong to care rights, some to refund or rerouting, and some may be weaker because they are consequential and not directly covered by [flight delay compensation](/en/flight-delay-compensation) rules.", "Do not put everything into one unclear amount. Send the airline a clean table: type of cost, amount, date, reason, proof and link to the delay."], bullets: commonBullets.en },
      { heading: "Costs during the wait", body: ["The simplest costs are those incurred while waiting: food, water, communication, basic hotel and transfer to the hotel. They should be reasonable in relation to waiting time, time of day and available options at the airport.", "If the airline gives a voucher but it is not enough, keep both the voucher and additional receipts. If the airport has no open shops or a restaurant does not accept the voucher, record that immediately."] },
      { heading: "A new ticket or other transport", body: ["Buying a replacement ticket yourself is riskier than a meal or hotel. Before doing that, ask the airline for rerouting and keep proof that no solution was offered, that it was unreasonably late or that it no longer served the purpose of the journey.", "If you still have to buy a new flight, bus or train, keep the search for reasonable options, price, departure time and reason why that option was chosen."] },
      { heading: "Parking, taxi and additional transfers", body: ["Parking and taxi costs may be justified when they are a direct consequence of the delay, for example when the flight returns late at night, when public transport is no longer running or when the passenger is rerouted to another airport. The link must be clear.", "In the claim, explain why the transfer was necessary, where it started and ended, and how it connects to the new arrival time. A taxi receipt alone is not always enough."] },
      { heading: "How Let Kasni prepares the cost file", body: ["First, we check whether arrival opens the fixed compensation question. Then receipts are divided into care during the wait, rerouting, new ticket and consequential costs. Each item gets a short evidence note.", "This approach is slower than sending one photo of all receipts, but it is much stronger. The passenger gets a file that clearly shows what is requested, why it is requested and which evidence supports each item.", "If the cost came from a lost hotel night, late arrival at work or missed private transfer, it should not be mixed with basic care rights. Those items are marked as additional loss and reviewed more cautiously. Sometimes they should not be placed in the first claim because they can distract from stronger items such as meals, hotel, transfer or a necessary replacement ticket."] },
      { heading: "How to send the request", body: ["The best order is basic flight evidence first, then a table of receipts, then a short explanation for every item. If a receipt is in another person's name from the same booking, add proof that the passenger was part of the same journey.", "When several passengers are involved, do not automatically multiply every cost. Some receipts apply per person, others per room or ride, so the file should show what is shared and what is an individual claim."] },
    ] },
  },
  {
    id: "rerouting-another-airline-flight-delay",
    publishedAt: "2026-05-14",
    updatedAt: "2026-05-14",
    sr: { slug: "preusmeravanje-druga-aviokompanija-kasnjenje-leta", title: "Preusmeravanje na drugu aviokompaniju posle kašnjenja leta", description: "Kada treba tražiti preusmeravanje na drugi let ili drugu aviokompaniju, kako dokumentovati ponudu i kako to utiče na naknadu.", excerpt: "Kod velikog kašnjenja najvažnije je šta je aviokompanija ponudila, kada stižete na krajnju destinaciju i da li je zamena bila razumna.", category: "Preusmeravanje", readTime: "8 min čitanja", sections: [
      { heading: "Kada preusmeravanje postaje glavno pitanje", body: ["Kada kašnjenje ugrozi konekciju, poslovni termin, porodični događaj ili nastavak putovanja, pitanje više nije samo čekanje. Putnik treba da zna da li može tražiti preusmeravanje, da li mora prihvatiti prvi ponuđeni let i kako se kasniji dolazak računa za [naknadu za kašnjenje leta](/naknada-za-kasnjenje-leta).", "Najvažnija činjenica je dolazak na krajnju destinaciju. Ako vas aviokompanija prebaci na drugi let, drugačiji itinerer ili drugu aviokompaniju, treba uporediti planirani dolazak sa stvarnim dolaskom posle zamene."], bullets: commonBullets.sr },
      { heading: "Druga aviokompanija ili kasniji let iste kompanije", body: ["Aviokompanija će najčešće prvo ponuditi kasniji let iste kompanije ili partnera. U nekim situacijama razumno rešenje može biti i drugi prevoznik, posebno ako je razlika u dolasku velika.", "Ako ponuđeni let stiže mnogo kasnije, pitajte da li postoji ranija opcija. Ako sami nađete raniji let kod druge kompanije, sačuvajte screenshot pretrage pre kupovine, ali imajte u vidu da refundacija takve karte nije automatska."] },
      { heading: "Jedna rezervacija i konekcije", body: ["Kod jedne rezervacije aviokompanija treba da posmatra put do poslednje destinacije, ne samo prvi segment. Ako kašnjenje prvog leta uništi konekciju, tražite novi itinerer do kraja puta.", "Kod odvojenih karata situacija je slabija. Prvi let se i dalje može proveriti, ali posledice po drugi, zasebno kupljen let obično nisu isto pokrivene."] },
      { heading: "Kako preusmeravanje utiče na iznos", body: ["Ako stignete na krajnju destinaciju kasno i ruta je pokrivena, i dalje se proverava fiksna naknada. Kod nekih preusmeravanja iznos može zavisiti od toga koliko kasno stižete u odnosu na prvobitni plan.", "Zahtev treba da sadrži originalni itinerer i novi itinerer. Bez oba dokumenta nije jasno šta se poredi. Ako je aviokompanija promenila i aerodrom dolaska, dodajte dokaz transfera."] },
      { heading: "Dokazi pre kupovine sopstvene zamene", body: ["Ako razmišljate da sami kupite novi let, prvo sačuvajte dokaz da ste tražili rešenje od aviokompanije. Zatim sačuvajte dostupne opcije, cene i vreme dolaska.", "Let Kasni kod ovakvih slučajeva proverava da li je samostalna zamena bila nužna, razumna i povezana sa kašnjenjem. Cilj je da se ne izgubi jak deo zahteva zbog loše dokumentovane hitne odluke.", "U praksi je korisno napraviti tri snimka ekrana: razgovor ili šalter gde tražite pomoć, opcije koje aviokompanija nudi i alternativni let koji sami nalazite. Ako je razlika između ponuđenog i kupljenog leta samo mala pogodnost, refundacija je slabija. Ako razlika znači dolazak istog dana umesto sutra, ili spasavanje konekcije iz jedne rezervacije, argument je znatno ozbiljniji."] },
      { heading: "Kada ne treba žuriti sa kupovinom", body: ["Ne treba žuriti sa kupovinom ako aviokompanija već organizuje realnu zamenu u razumnom roku. Tada je bolje tražiti pisanu potvrdu ponude, proveriti krajnji dolazak i sačuvati troškove čekanja.", "Kupovina sopstvenog leta ima više smisla kada ponuđena opcija ne rešava putovanje, kada propuštate povezane segmente iz iste rezervacije ili kada osoblje jasno kaže da nema rešenja. I tada cena mora ostati razumna u odnosu na dostupne alternative. Ako kupujete za više putnika, sačuvajte dokaz da svi pripadaju istoj rezervaciji ili istom poremećenom putu. U suprotnom kompanija može priznati samo deo troška ili tražiti dodatna ovlašćenja pre bilo kakve isplate. Ako je zamena kupljena za porodicu ili grupu, navedite ko je putovao, koji su brojevi karata i zašto je jedna kupovina pokrila sve putnike. To čini zahtev proverljivim i smanjuje kasnije dopune. Ako je rok za polazak blizu, zapišite i vreme kada ste kupili zamenu, jer pokazuje da odluka nije doneta pre nego što je aviokompanija imala priliku da ponudi rešenje."] },
    ] },
    en: { slug: "rerouting-another-airline-flight-delay", title: "Rerouting to another airline after a flight delay", description: "When to request rerouting to another flight or airline, how to document the offer and how it affects compensation.", excerpt: "During a major delay, the key facts are what the airline offered, when you reach the final destination and whether the replacement was reasonable.", category: "Rerouting", readTime: "8 min read", sections: [
      { heading: "When rerouting becomes the main issue", body: ["When a delay threatens a connection, business appointment, family event or onward journey, the issue is no longer only waiting. Passengers need to know whether they can request rerouting, whether they must accept the first offered flight and how later arrival is counted for [flight delay compensation](/en/flight-delay-compensation).", "The most important fact is arrival at the final destination. If the airline moves you to another flight, different itinerary or another airline, compare scheduled arrival with actual arrival after the replacement."], bullets: commonBullets.en },
      { heading: "Another airline or a later flight on the same airline", body: ["The airline will usually first offer a later flight on the same airline or a partner. In some situations, another carrier may be the reasonable solution, especially if the arrival difference is large.", "If the offered flight arrives much later, ask whether an earlier option exists. If you find an earlier flight on another airline yourself, keep a search screenshot before buying, but remember that reimbursement of that ticket is not automatic."] },
      { heading: "One booking and connections", body: ["Under one booking, the airline should consider the journey to the final destination, not only the first segment. If the first flight delay destroys the connection, request a new itinerary to the end of the journey.", "With separate tickets, the position is weaker. The first flight may still be checked, but consequences for a second separately bought flight are usually not covered in the same way."] },
      { heading: "How rerouting affects the amount", body: ["If you reach the final destination late and the route is covered, fixed compensation is still checked. For some rerouting cases, the amount may depend on how late you arrive compared with the original plan.", "The claim should include the original itinerary and the new itinerary. Without both documents, it is unclear what is being compared. If the airline also changed the arrival airport, add proof of transfer."] },
      { heading: "Evidence before buying your own replacement", body: ["If you are considering buying a new flight yourself, first keep proof that you asked the airline for a solution. Then save available options, prices and arrival times.", "In these cases, Let Kasni checks whether the self-bought replacement was necessary, reasonable and linked to the delay. The goal is to avoid losing a strong part of the claim because an urgent airport decision was poorly documented.", "In practice, keep three screenshots: the conversation or desk interaction where you ask for help, the options the airline offers and the alternative flight you find yourself. If the difference is only a small convenience, reimbursement is weaker. If it means arriving the same day instead of tomorrow, or preserving a connection under one booking, the argument is much stronger."] },
      { heading: "When not to rush into buying", body: ["Do not rush into buying a new ticket if the airline is already arranging a realistic replacement within a reasonable time. It is better to request written confirmation of the offer, check final arrival and keep waiting-cost receipts.", "A self-bought flight makes more sense when the offered option does not solve the trip, when you lose connected segments under one booking or when staff clearly say there is no solution. Even then, the price should remain reasonable compared with available alternatives."] },
    ] },
  },
] satisfies BlogArticle[];
