// Tekst nove verzije sajta (v2 iz transport-local, Niko 26.09.2026: „menjamo brend i UX“) za header, footer i
// početnu, u paru SR/EN. Proveravaju ga `npm run locales:check` i `npm run copy:rules`.
// Dizajn je 1:1 sa originalom (Niko 27.09: „drži originalni dizajn 1:1, dodaj i zvezdice“). Odstupanja su samo u tekstu,
// zbog Nikovih pravila: iskustva putnika su bez rokova isplate i bez „brzo“, odgovor o ceni usluge je sadašnji
// (bez „do kraja letnje sezone“), a brend se piše „Letkasni.rs“.
export const copy = {
  sr: {
    page: {
      skip: "Pređite na sadržaj",
    },
    sticky: {
      aria: "Brza provera leta",
      title: "Proverite pravo na naknadu do 600 €.",
      body: "Za letove do i iz Srbije · Besplatna provera",
      button: "Započnite proveru",
    },
    inner: {
      breadcrumbAria: "Putanja",
      home: "Početna",
      blog: "Blog",
      tocTitle: "Sadržaj stranice",
      tocAria: "Sadržaj",
      tocButton: "Proverite let →",
      guideButton: "Proverite svoj let →",
      guideMore: "Saznajte više ↓",
      guideBadge: "PRAVA PUTNIKA",
      faqTitle: "Česta pitanja",
      detailedGuides: "Detaljni vodiči",
      readArticle: "Pročitajte tekst →",
      updated: "Ažurirano",
      mainGuide: "Glavni vodič za ovu temu",
      legalBadge: "PRAVNE INFORMACIJE",
    },
    blogIndex: {
      badge: "BLOG",
      title: "Saveti za mirnije putovanje.",
      lead: "Prava putnika, praktični koraci i odgovori na pitanja o Vašem letu.",
      searchLabel: "Pretražite tekstove",
      searchPlaceholder: "Npr. kašnjenje, prtljag, dokumentacija",
      topicLabel: "Tema",
      topicApply: "Prikažite temu",
      count: "Pronađeno tekstova:",
      emptyTitle: "Nema tekstova za ovu pretragu.",
      emptyBody: "Pokušajte sa drugom reči ili temom.",
      reset: "Poništite pretragu",
      prev: "← Prethodna",
      next: "Sledeća →",
      pagesAria: "Stranice bloga",
    },
    contactPage: {
      badge: "KONTAKT",
      title: "Tu smo za Vaša pitanja.",
      lead: "Pišite nam ili nas pozovite. Za proveru konkretnog leta možete odmah započeti prijavu.",
      emailBadge: "E-MAIL",
      emailTitle: "Pišite nam",
      emailBody: "Za pitanja o letu i toku Vašeg predmeta.",
      phoneBadge: "TELEFON",
      phoneTitle: "Razgovarajte sa nama",
      phoneBody: "Podrška na srpskom jeziku.",
      claimBadge: "PRIJAVA",
      claimTitle: "Prijavite svoj let",
      claimBody: "Unesite podatke o putovanju u našoj formi.",
      claimLink: "Započnite prijavu →",
      companyTitle: "Podaci o kompaniji",
      pib: "PIB",
      mb: "Matični broj",
    },
    aboutPage: {
      badge: "O NAMA",
      title: "Vaš let. Naša briga.",
      lead: "Lokalna podrška za putnike sa letovima do i iz Srbije.",
      imageAlt: "Ilustrativni prikaz kancelarije",
      heading: "Podrška na srpskom, od provere do sledećeg koraka.",
      body: [
        "Letkasni.rs pomaže putnicima da provere mogućnost naknade i pripreme svoj predmet. Proveravamo okolnosti konkretnog leta i potrebnu dokumentaciju.",
        "Uslugu pruža VGA EU CONSULTING DOO NIŠ. Model vođenja konkretnog predmeta uređen je ugovorom i opštim uslovima poslovanja.",
      ],
      termsLink: "Pročitajte uslove poslovanja →",
    },
    faqPage: {
      badge: "PODRŠKA",
      title: "Česta pitanja",
      lead: "Od prve provere leta do vođenja postupka.",
      heading: "Česta pitanja o kašnjenju leta",
      intro: "Odgovori koji Vam pomažu da pripremite zahtev.",
      items: [
        {
          id: "lk-faq-arrival",
          q: "Da li se računa kašnjenje pri poletanju ili dolasku?",
          a: "Za fiksnu naknadu najvažniji je dolazak na krajnju destinaciju. Kod povezanih letova na jednoj rezervaciji proveravamo celo putovanje.",
        },
        {
          id: "lk-faq-weather",
          q: "Da li loše vreme automatski znači da nema naknade?",
          a: "Ne automatski. Potrebno je proveriti gde je nastalo, koliko je trajalo i da li je direktno uticalo na Vaš let. Razlog naveden bez konkretnog objašnjenja nije dovoljan za pouzdanu procenu.",
        },
        {
          id: "lk-faq-serbia",
          q: "Da li možete da proverite let iz Srbije?",
          a: "Da. Pošaljite rutu, datum i broj leta. Proveravamo avio-kompaniju, eventualne konekcije i pravila koja se primenjuju na konkretno putovanje.",
        },
        {
          id: "lk-faq-cost",
          q: "Koliko košta Vaša usluga?",
          a: "Ponuda bez troškova i provizije odnosi se na promotivni period. Uslove koji važe za Vaš predmet potvrđujemo pre pokretanja postupka.",
        },
        {
          id: "lk-faq-rejected",
          q: "Avio-kompanija je odbila zahtev. Šta dalje?",
          a: "Sačuvajte njihov odgovor i dostavite ga uz podatke o letu. Odbijanje ne znači samo po sebi da nema osnova: proveravamo obrazloženje i raspoložive dokaze.",
        },
        {
          id: "lk-faq-duration",
          q: "Koliko traje postupak?",
          a: "Trajanje zavisi od avio-kompanije, dokumentacije i toga da li je potreban sudski postupak. O važnim koracima i statusu Vašeg predmeta dobijate obaveštenja.",
        },
      ],
      notePrefix: "Više o evropskim pravilima:",
      noteLink: "Your Europe — prava avio-putnika",
      noteSuffix: "Primena zavisi od rute i okolnosti leta.",
    },
    emailOffersPage: {
      badge: "E-MAIL PONUDE",
      manageTitle: "Upravljanje e-mail ponudama",
      confirmTitle: "Potvrda prijave za ponude",
      lead: "Pristanak na ponude odvojen je od obrade Vašeg predmeta.",
      heading: "Vaš izbor ostaje Vaš.",
      privacyLink: "Politika privatnosti →",
    },
    delayPage: {
      nav: [
        { href: "#kako-radi", label: "Kako radi" },
        { href: "#uslovi", label: "Uslovi za naknadu" },
        { href: "#faq", label: "Česta pitanja" },
      ],
      heroBadge: "BEZ TROŠKOVA I PROVIZIJE*",
      heroTitleA: "Naknada za ",
      heroTitleB: "kašnjenje leta",
      heroPromise: "Proverite pravo na naknadu do 600 € po putniku.",
      checksTitle: "Let je kasnio. Šta proveravamo?",
      checksIntro: "Tri stvari su važne za procenu Vašeg slučaja.",
      checks: [
        {
          icon: "clock",
          title: "Dolazak na odredište",
          body: "Za fiksnu naknadu važan je dolazak na krajnju destinaciju, a ne samo kašnjenje pri poletanju. Dolazak tri sata ili više kasnije razlog je da proverite let.",
        },
        {
          icon: "airplane",
          title: "Ruta i avio-kompanija",
          body: "Proveravamo polazni i odredišni aerodrom, prevoznika i eventualna presedanja. Za Srbiju i ECAA pravni osnov razmatramo zasebno.",
        },
        {
          icon: "shield",
          title: "Razlog kašnjenja",
          body: "Tehnički i operativni problemi mogu biti odgovornost prevoznika. Vanredne okolnosti mogu isključiti fiksnu naknadu; proveravamo konkretne činjenice.",
        },
      ],
      amountsTitle: "Koliku naknadu možete da dobijete?",
      amountsIntro: "250, 400 ili do 600 € — u zavisnosti od Vaše rute.",
      amounts: [
        { badge: "Do 1.500 km", amount: "250", body: "Kraće rute obuhvaćene pravilima o naknadi." },
        { badge: "Srednje rute", amount: "400", body: "Letovi unutar EU duži od 1.500 km i druge rute od 1.500 do 3.500 km." },
        { badge: "Duge rute", amount: "600", body: "Ostale rute preko 3.500 km. U određenim okolnostima iznos može biti umanjen." },
      ],
      amountsNote:
        "Iznosi su po putniku i ne zavise od cene karte. Pravo i konačan iznos zavise od primenljivih pravila, kašnjenja i okolnosti konkretnog leta.",
      amountsButton: "Proverite svoj let",
      docsTitle: "Sačuvajte ono što potvrđuje Vaš let.",
      docsIntro: "Za početak su dovoljni broj leta, datum i opis problema. Ova dokumenta pomažu daljoj proveri.",
      docs: [
        {
          icon: "airplane",
          title: "Karta i rezervacija",
          body: "Sačuvajte potvrdu rezervacije i kartu za ukrcavanje. Kod presedanja važno je da se vidi da li su letovi bili na jednoj rezervaciji.",
        },
        {
          icon: "chat",
          title: "Poruke i vreme dolaska",
          body: "Sačuvajte obaveštenja avio-kompanije, fotografiju statusa leta i objašnjenje razloga kašnjenja koje ste dobili.",
        },
        {
          icon: "check-filled",
          title: "Računi za troškove",
          body: "Sačuvajte račune za hranu, smeštaj i prevoz tokom čekanja, kao i dokaz da ste od kompanije tražili pomoć.",
        },
      ],
      careTitle: "Još ste na aerodromu?",
      careIntro: "Pravo na pomoć tokom čekanja i fiksna naknada nisu isti zahtev.",
      care: [
        {
          badge: "TOKOM ČEKANJA",
          title: "Zatražite pomoć od avio-kompanije.",
          body: "U zavisnosti od trajanja kašnjenja i rute, pomoć može uključivati obroke i osveženje, a kada je potrebno i noćenje sa prevozom. Sačuvajte račune i prepisku.",
        },
        {
          badge: "NAKON PUTOVANJA",
          title: "Proverite pravo na naknadu.",
          body: "To što ste dobili obrok ili hotel ne rešava pitanje fiksne naknade. Takođe, vanredne okolnosti koje isključuju naknadu ne moraju da ukinu pravo na pomoć.",
        },
      ],
      faqTitle: "Česta pitanja o kašnjenju leta",
      faqIntro: "Odgovori koji Vam pomažu da pripremite zahtev.",
    },
    notFound: {
      badge: "404",
      title: "Stranica nije pronađena",
      lead: "Ova stranica više nije dostupna ili adresa nije ispravna. Možete pročitati više o pravima putnika ili proveriti svoj let.",
      rights: "Prava putnika",
      check: "Proverite let",
    },
    header: {
      homeAria: "Letkasni.rs — početna",
      logoAlt: "Letkasni.rs",
      navAria: "Glavna navigacija",
      mobileNavAria: "Mobilna navigacija",
      nav: [
        { to: "#kako-radi", label: "Kako radi" },
        { to: "#prednosti", label: "Prednosti" },
        { to: "faq", label: "Česta pitanja" },
      ],
      blog: "Blog",
      localeLabel: "EN",
      localeAria: "English version",
      mobileLocale: "English version",
      cta: "Proverite let",
      menuOpen: "Otvorite meni",
      menuClose: "Zatvorite meni",
    },
    hero: {
      badge: "BEZ TROŠKOVA I PROVIZIJE*",
      titleA: "Pomeren ili ",
      titleB: "otkazan let?",
      promise: "Naplatite do 600 €. Zadržite ceo iznos.",
      formBadge: "BESPLATNA PROVERA",
      question: "Šta se dogodilo sa Vašim letom?",
      legend: "Vrsta problema sa letom",
      issues: [
        { label: "Let je kasnio 3+ sata", note: "" },
        { label: "Let je otkazan", note: "" },
        { label: "Drugi problem", note: "(npr. odbijen ukrcaj, štrajk, prtljag…)" },
      ],
      error: "Izaberite problem sa letom da biste nastavili.",
      button: "Započnite proveru",
      proof: ["Bez troškova i provizije*", "Lokalna podrška"],
      promoNote: "* U promotivnom periodu.",
      promoLink: "Pogledajte uslove usluge.",
    },
    steps: {
      eyebrow: "KAKO RADI",
      title: "Tri koraka do Vaše odštete.",
      body: "Manje papirologije za Vas. Podrška tokom celog postupka.",
      items: [
        {
          title: "Unesite podatke",
          body: "Broj leta, datum i osnovni problem. Za početak je dovoljno samo nekoliko informacija.",
        },
        {
          title: "Mi proveravamo slučaj",
          body: "Proveravamo okolnosti leta. Advokat utvrđuje da li postoji osnov za potraživanje naknade.",
        },
        {
          title: "Postupak i isplata",
          body: "Vodimo postupak i obaveštavamo Vas o statusu. Po uspešnoj naplati, naknada stiže na Vaš račun.",
        },
      ],
    },
    promo: {
      badge: "TRENUTNA PONUDA",
      titleA: "Bez troškova i provizije*",
      titleB: "Ceo iznos naknade ide Vama.",
      compareOtherLabel: "Druge platforme uzimaju:",
      compareOtherPct: "30–50%",
      compareUsLabel: "Letkasni.rs:",
      compareUsPct: "0%",
      button: "Proverite let besplatno",
      note: "* U promotivnom periodu.",
    },
    compensation: {
      aria: "Iznosi naknade i brza provera",
      amountsTitle: "Koliko možete da dobijete?",
      amountsBody: "Naknada zavisi od dužine leta i okolnosti. Iznos se računa po putniku i ne zavisi od cene karte.",
      amountsButton: "Proverite svoj let",
      tiers: [
        { label: "Do 1.500 km", amount: "do 250 €", example: "npr. Beograd – Beč, Beograd – Cirih" },
        { label: "1.500–3.500 km", amount: "do 400 €", example: "npr. Beograd – London, Beograd – Madrid" },
        { label: "Preko 3.500 km", amount: "do 600 €", example: "npr. Beograd – Njujork, Beograd – Čikago" },
      ],
      amountsNote:
        "Navedeni iznosi su najviši mogući po putniku. Na dužim rutama i u posebnim okolnostima iznos može biti umanjen, zato svaki slučaj proveravamo pojedinačno.",
      phoneTitle: "Proverite svoj let",
      phoneBody: "Izaberite šta se dogodilo i unesite osnovne podatke o letu. Ostalo preuzimamo mi.",
      phoneButton: "Započnite proveru",
      phoneAria: "Primer mobilne provere: izbor problema sa letom",
      phoneBadge: "BESPLATNA PROVERA",
      phoneQuestion: "Šta se dogodilo sa Vašim letom?",
      phoneOptions: ["Let je kasnio 3+ sata", "Let je otkazan", "Drugi problem"],
      phoneNext: "Započnite proveru →",
    },
    benefits: {
      title: "Zašto putnici biraju Letkasni.rs?",
      body: "Vaš slučaj zaslužuje nekoga ko razume i putnika i lokalne procedure.",
      items: [
        {
          title: "Srbija je naš fokus",
          body: "Specijalizovani smo za letove do i iz Srbije. Poznajemo lokalne procedure i način rešavanja zahteva.",
        },
        {
          title: "Podrška na srpskom",
          body: "Razgovarate sa ljudima koji poznaju Vaš slučaj. Dobijate jasne odgovore na svoja pitanja.",
        },
        {
          title: "Postupak u stručnim rukama",
          body: "Advokat utvrđuje da li postoji osnov za naknadu. Vodimo Vas kroz potrebne korake i komunikaciju sa avio-kompanijom.",
        },
        {
          title: "Jednostavan početak",
          body: "Za početak su dovoljni broj leta, datum i osnovni problem. Kroz proveru Vas vodimo korak po korak.",
        },
        {
          title: "Manje papirologije za Vas",
          body: "Dostavite potrebne podatke i dokumentaciju. Mi preuzimamo komunikaciju i vođenje postupka.",
        },
        {
          title: "Znate kako napreduje slučaj",
          body: "Obaveštavamo Vas o statusu zahteva i sledećim koracima. Podrška je tu tokom celog postupka.",
        },
      ],
      button: "Proverite let besplatno",
      link: "Pogledajte kako radi",
    },
    airlines: {
      badge: "0% provizije — ceo iznos ostaje Vama*",
      title: "Vodimo zahteve prema svim većim avio-kompanijama.",
      body: "Vodimo slučajeve za letove iz i za Srbiju, bez obzira na cenu karte.",
      points: ["Srpsko tržište je naš fokus", "Lokalni ljudi, direktna podrška", "Advokat vodi Vaš predmet"],
      button: "Proverite odštetu",
      note: "* U promotivnom periodu.",
      noteLink: "Pogledajte uslove usluge.",
      listAria: "Avio-kompanije",
    },
    quickCheck: {
      titleA: "Vi nastavite putovanje,",
      titleB: "papirologiju prepustite nama.",
      badge: "BESPLATNA PROVERA",
      subtitle: "Proverite svoj let",
      body: "Izaberite šta se dogodilo i unesite osnovne podatke o letu. Ostalo preuzimamo mi.",
      points: ["Besplatna provera", "0% provizije u promotivnom periodu*"],
      button: "Proverite let",
      noteLink: "Pogledajte uslove usluge.",
      imageAlt: "Nasmejan par zajedno gleda u telefon",
    },
    localSupport: {
      badge: "KONTAKT",
      title: "Lokalni tim, direktna podrška",
      body: "Kašnjenje već uzme dovoljno vremena. Mi pišemo avio-kompaniji, pratimo rokove i odgovaramo na odbijanja, a Vi o svakom važnom koraku dobijate obaveštenje.",
      points: ["Pišete i razgovarate na srpskom", "Lokalni tim, direktna podrška", "O svakom važnom koraku Vas obaveštavamo"],
      contactLead: "Imate pitanje? Javite nam se:",
      imageAlt: "Svetla kancelarija sa radnim stolom i biljkama — ilustrativna fotografija",
    },
    testimonials: {
      eyebrow: "ISKUSTVA PUTNIKA",
      titleA: "Utisci ",
      titleB: "naših klijenata.",
      role: "Putnik",
      outcome: "Naknada po putniku",
      ratingAria: "Ocena: 5 od 5 zvezdica",
      items: [
        {
          name: "Miloš Nikolić",
          route: "Niš – Beč",
          amount: "250 €",
          quote:
            "Posle otkazanog leta nisam znao kome da pišem ni šta da tražim. Pozvao sam kontakt telefon, Bojana iz podrške mi je sve lepo objasnila, poslao sam dokumentaciju i to je bilo to.",
        },
        {
          name: "Lazar Miučin",
          route: "Beograd – London",
          amount: "400 €",
          quote: "Dobio sam preporuku da je sve profi jer stvarno rade naši ljudi. Tako je i bilo, i 400 EUR mi je leglo na račun. :)",
        },
        {
          name: "Nikola Marinić",
          route: "Beograd – Njujork",
          amount: "600 €",
          quote:
            "Imali smo propuštenu konekciju zbog kašnjenja - mikro haos u životu i milion pitanja šta dalje. Odmah sam upućen na srpskog advokata koji je vrlo profesionalno odradio svoj posao. Isplaćeno nam je 2400 EUR za čitavu porodicu.",
        },
      ],
    },
    faq: {
      title: "Česta pitanja",
      items: [
        {
          q: "Koliko novca mogu da dobijem?",
          a: "Po pravilima EU 261/2004 odšteta je najčešće 250, 400 ili 600 € po putniku, u zavisnosti od dužine leta i okolnosti kašnjenja. Cena karte ne utiče na iznos.",
        },
        {
          q: "Koliko košta Vaša usluga?",
          a: "Ponuda bez troškova i provizije odnosi se na promotivni period. Uslove koji važe za Vaš predmet potvrđujemo pre pokretanja postupka. Ukoliko slučaj ode pred sud, advokat koji vodi Vaš predmet naplaćuje se isključivo od avio-kompanije.",
        },
        {
          q: "Šta mi je potrebno za proveru?",
          a: "Za prvi korak dovoljni su broj leta, datum i osnovni opis problema. Dodatna dokumenta tražimo nakon početne provere slučaja.",
        },
        {
          q: "Šta ako je avio-kompanija već odbila zahtev?",
          a: "Odbijanje zahteva ne mora da znači da nemate pravo na naknadu. Radimo sopstvenu proveru okolnosti leta pre odluke o daljem postupku.",
        },
        {
          q: "Koliko traje postupak?",
          a: "Trajanje zavisi od avio-kompanije i okolnosti slučaja. Predmeti koji zahtevaju dodatne provere ili sudski postupak mogu trajati duže. O statusu Vašeg zahteva redovno Vas obaveštavamo.",
        },
        {
          q: "Mogu li da tražim odštetu za stariji let?",
          a: "Moguće je, u zavisnosti od datuma leta i pravila koja se primenjuju na konkretan slučaj. Pošaljite podatke o letu kako bismo proverili da li zahtev još može da se podnese.",
        },
      ],
    },
    supportHighlights: {
      title: "Tu smo za Vas.",
      body: "Za sva pitanja o Vašem letu i predmetu, javite nam se — pišemo i razgovaramo na srpskom.",
      items: [
        { title: "24/7", body: "Prijavu možete poslati u bilo koje doba." },
        { title: "Podrška na srpskom", body: "Pišete i razgovarate sa našim timom na srpskom jeziku." },
        { title: "Advokat vodi postupak", body: "Advokat utvrđuje osnov i vodi komunikaciju sa avio-kompanijom." },
      ],
    },
    cta: {
      badge: "BESPLATNA PROVERA",
      titleA: "Ne ostavljajte novac",
      titleB: "avio-kompaniji.",
      body: "Proverite svoj let. Mi preuzimamo sledeće korake.",
      button: "Proverite let besplatno",
      artTitle: "Primer provere leta: kašnjenje 4 sata i 12 minuta, moguća naknada do 600 evra. Iznos zavisi od provere slučaja.",
      artFlightLabel: "BROJ VAŠEG LETA",
      artExample: "PRIMER PROVERE",
      artStatus: "KAŠNJENJE · 4 h 12 min",
      artRoute: "BEG → JFK · 14. mart",
      artAmountLabel: "Moguća naknada",
      artAmount: "do 600 €",
      artAmountNote: "Iznos potvrđujemo nakon provere slučaja.",
      artChecks: ["Besplatna provera", "Lokalna podrška", "Na srpskom"],
    },
    blog: {
      eyebrow: "SAVETI ZA PUTNIKE",
      title: "Najnovije sa bloga.",
      all: "Svi tekstovi",
      read: "Pročitajte tekst",
    },
    footer: {
      socialAria: "Društvene mreže",
      officeTitle: "Vaš let. Naša briga.",
      officeBody: "Proverite mogućnost naknade do 600 € po putniku. Mi preuzimamo komunikaciju i vođenje postupka.",
      officeButton: "Započnite proveru",
      supportEyebrow: "LOKALNA PODRŠKA",
      brandColumn: "Letkasni.rs",
      brandLinks: [
        { to: "about", label: "O nama" },
        { to: "#kako-radi", label: "Kako radi" },
        { to: "#prednosti", label: "Zašto Letkasni.rs" },
        { to: "#iskustva", label: "Iskustva putnika" },
        { to: "faq", label: "Česta pitanja" },
        { to: "blog", label: "Blog" },
        { to: "contact", label: "Kontakt" },
      ],
      rightsColumn: "Prava putnika",
      rightsLinks: [
        { guide: "air-passenger-rights", label: "Prava putnika" },
        { guide: "flight-delay-compensation", label: "Kašnjenje leta" },
        { guide: "flight-cancellation-compensation", label: "Otkazan let" },
        { guide: "missed-connection-compensation", label: "Propuštena konekcija" },
      ],
      otherColumn: "Ostali problemi sa letom",
      otherLinks: [
        { guide: "overbooking-compensation", label: "Overbooking" },
        { guide: "denied-boarding-compensation", label: "Uskraćeno ukrcavanje" },
        { guide: "delayed-baggage-compensation", label: "Kašnjenje prtljaga" },
        { guide: "airline-strike-compensation", label: "Štrajk avio-kompanije" },
      ],
      copyright: "© 2026 Letkasni.rs. Sva prava zadržana.",
      terms: "Uslovi korišćenja",
      privacy: "Politika privatnosti",
      emailOffers: "E-mail ponude",
      privacySettings: "Podešavanja privatnosti",
    },
  },
  en: {
    page: {
      skip: "Skip to content",
    },
    sticky: {
      aria: "Quick flight check",
      title: "Check your right to compensation of up to €600.",
      body: "For flights to and from Serbia · Free check",
      button: "Start the check",
    },
    inner: {
      breadcrumbAria: "Breadcrumb",
      home: "Home",
      blog: "Blog",
      tocTitle: "On this page",
      tocAria: "Contents",
      tocButton: "Check your flight →",
      guideButton: "Check your flight →",
      guideMore: "Learn more ↓",
      guideBadge: "PASSENGER RIGHTS",
      faqTitle: "Frequently asked questions",
      detailedGuides: "Detailed guides",
      readArticle: "Read the article →",
      updated: "Updated",
      mainGuide: "Main guide for this topic",
      legalBadge: "LEGAL INFORMATION",
    },
    blogIndex: {
      badge: "BLOG",
      title: "Tips for calmer travel.",
      lead: "Passenger rights, practical steps and answers to questions about your flight.",
      searchLabel: "Search articles",
      searchPlaceholder: "E.g. delay, baggage, documents",
      topicLabel: "Topic",
      topicApply: "Show topic",
      count: "Articles found:",
      emptyTitle: "No articles match this search.",
      emptyBody: "Try another word or topic.",
      reset: "Clear search",
      prev: "← Previous",
      next: "Next →",
      pagesAria: "Blog pages",
    },
    contactPage: {
      badge: "CONTACT",
      title: "We are here for your questions.",
      lead: "Write to us or call us. To check a specific flight, you can start your claim right away.",
      emailBadge: "EMAIL",
      emailTitle: "Write to us",
      emailBody: "For questions about your flight and the progress of your case.",
      phoneBadge: "PHONE",
      phoneTitle: "Talk to us",
      phoneBody: "Support in Serbian and English.",
      claimBadge: "CLAIM",
      claimTitle: "Submit your flight",
      claimBody: "Enter your trip details in our form.",
      claimLink: "Start your claim →",
      companyTitle: "Company details",
      pib: "Tax ID (PIB)",
      mb: "Registration number",
    },
    aboutPage: {
      badge: "ABOUT US",
      title: "Your flight. Our care.",
      lead: "Local support for passengers flying to and from Serbia.",
      imageAlt: "Illustrative photo of an office",
      heading: "Support in your language, from the first check to the next step.",
      body: [
        "Letkasni.rs helps passengers check whether they can claim compensation and prepare their case. We review the circumstances of the specific flight and the documents it needs.",
        "The service is provided by VGA EU CONSULTING DOO NIŠ. How each case is handled is set out in the contract and the general terms of business.",
      ],
      termsLink: "Read the terms of business →",
    },
    faqPage: {
      badge: "SUPPORT",
      title: "Frequently asked questions",
      lead: "From the first flight check to running the claim.",
      heading: "Frequently asked questions about flight delays",
      intro: "Answers that help you prepare your claim.",
      items: [
        {
          id: "lk-faq-arrival",
          q: "Does the delay count at departure or at arrival?",
          a: "For fixed compensation, what matters most is arrival at the final destination. For connecting flights on one booking, we check the whole journey.",
        },
        {
          id: "lk-faq-weather",
          q: "Does bad weather automatically mean there is no compensation?",
          a: "Not automatically. We need to check where it happened, how long it lasted and whether it directly affected your flight. A reason given without a concrete explanation is not enough for a reliable assessment.",
        },
        {
          id: "lk-faq-serbia",
          q: "Can you check a flight from Serbia?",
          a: "Yes. Send us the route, date and flight number. We check the airline, any connections and the rules that apply to the specific journey.",
        },
        {
          id: "lk-faq-cost",
          q: "How much does your service cost?",
          a: "The offer with no costs or commission applies during the promotional period. We confirm the terms that apply to your case before the claim starts.",
        },
        {
          id: "lk-faq-rejected",
          q: "The airline rejected my claim. What next?",
          a: "Keep their reply and send it together with your flight details. A rejection does not by itself mean there are no grounds: we check the reasoning and the available evidence.",
        },
        {
          id: "lk-faq-duration",
          q: "How long does the process take?",
          a: "It depends on the airline, the documents and whether court proceedings are needed. You get updates on the important steps and the status of your case.",
        },
      ],
      notePrefix: "More about the European rules:",
      noteLink: "Your Europe — air passenger rights",
      noteSuffix: "How they apply depends on the route and the circumstances of the flight.",
    },
    emailOffersPage: {
      badge: "EMAIL OFFERS",
      manageTitle: "Manage email offers",
      confirmTitle: "Confirm subscription",
      lead: "Consent to offers is separate from handling your case.",
      heading: "Your choice stays yours.",
      privacyLink: "Privacy policy →",
    },
    delayPage: {
      nav: [
        { href: "#kako-radi", label: "How it works" },
        { href: "#uslovi", label: "Eligibility" },
        { href: "#faq", label: "FAQ" },
      ],
      heroBadge: "NO COSTS OR COMMISSION*",
      heroTitleA: "Flight delay ",
      heroTitleB: "compensation",
      heroPromise: "Check your right to compensation of up to €600 per passenger.",
      checksTitle: "Your flight was delayed. What do we check?",
      checksIntro: "Three things matter when assessing your case.",
      checks: [
        {
          icon: "clock",
          title: "Arrival at the destination",
          body: "For fixed compensation, what counts is arrival at the final destination, not only the late departure. Arriving three hours or more late is a reason to check your flight.",
        },
        {
          icon: "airplane",
          title: "Route and airline",
          body: "We check the departure and destination airports, the carrier and any connections. For Serbia and ECAA routes we assess the legal basis separately.",
        },
        {
          icon: "shield",
          title: "Reason for the delay",
          body: "Technical and operational problems can be the carrier's responsibility. Extraordinary circumstances can rule out fixed compensation; we check the concrete facts.",
        },
      ],
      amountsTitle: "How much compensation can you get?",
      amountsIntro: "€250, €400 or up to €600 — depending on your route.",
      amounts: [
        { badge: "Up to 1,500 km", amount: "250", body: "Shorter routes covered by the compensation rules." },
        { badge: "Medium routes", amount: "400", body: "Flights within the EU longer than 1,500 km and other routes of 1,500 to 3,500 km." },
        { badge: "Long routes", amount: "600", body: "Other routes over 3,500 km. In certain circumstances the amount may be reduced." },
      ],
      amountsNote:
        "Amounts are per passenger and do not depend on the ticket price. The right and the final amount depend on the applicable rules, the delay and the circumstances of the specific flight.",
      amountsButton: "Check your flight",
      docsTitle: "Keep what confirms your flight.",
      docsIntro: "The flight number, date and a description of the problem are enough to start. These documents help the further review.",
      docs: [
        {
          icon: "airplane",
          title: "Ticket and booking",
          body: "Keep the booking confirmation and your boarding pass. With connections, it matters whether the flights were on one booking.",
        },
        {
          icon: "chat",
          title: "Messages and arrival time",
          body: "Keep the airline's notifications, a photo of the flight status and any explanation of the delay you received.",
        },
        {
          icon: "check-filled",
          title: "Receipts for expenses",
          body: "Keep receipts for food, accommodation and transport while waiting, and proof that you asked the airline for assistance.",
        },
      ],
      careTitle: "Still at the airport?",
      careIntro: "The right to assistance while waiting and fixed compensation are not the same claim.",
      care: [
        {
          badge: "WHILE WAITING",
          title: "Ask the airline for assistance.",
          body: "Depending on the length of the delay and the route, assistance can include meals and refreshments and, when needed, an overnight stay with transport. Keep receipts and correspondence.",
        },
        {
          badge: "AFTER THE TRIP",
          title: "Check your right to compensation.",
          body: "Getting a meal or a hotel does not settle the question of fixed compensation. Also, extraordinary circumstances that rule out compensation do not have to end the right to assistance.",
        },
      ],
      faqTitle: "Frequently asked questions about flight delays",
      faqIntro: "Answers that help you prepare your claim.",
    },
    notFound: {
      badge: "404",
      title: "Page not found",
      lead: "This page is no longer available, or the address is incorrect. You can read about your passenger rights or check your flight.",
      rights: "Passenger rights",
      check: "Check your flight",
    },
    header: {
      homeAria: "Letkasni.rs — home",
      logoAlt: "Letkasni.rs",
      navAria: "Main navigation",
      mobileNavAria: "Mobile navigation",
      nav: [
        { to: "#kako-radi", label: "How it works" },
        { to: "#prednosti", label: "Benefits" },
        { to: "faq", label: "FAQ" },
      ],
      blog: "Blog",
      localeLabel: "SR",
      localeAria: "Srpska verzija",
      mobileLocale: "Srpska verzija",
      cta: "Check your flight",
      menuOpen: "Open menu",
      menuClose: "Close menu",
    },
    hero: {
      badge: "NO COSTS OR COMMISSION*",
      titleA: "Delayed or ",
      titleB: "cancelled flight?",
      promise: "Claim up to €600. Keep the full amount.",
      formBadge: "FREE CHECK",
      question: "What happened to your flight?",
      legend: "Type of flight problem",
      issues: [
        { label: "Flight delayed 3+ hours", note: "" },
        { label: "Flight cancelled", note: "" },
        { label: "Another issue", note: "(e.g. denied boarding, strike, baggage…)" },
      ],
      error: "Choose what happened to your flight to continue.",
      button: "Start the check",
      proof: ["No costs or commission*", "Local support"],
      promoNote: "* During the promotional period.",
      promoLink: "See the terms of service.",
    },
    steps: {
      eyebrow: "HOW IT WORKS",
      title: "Three steps to your compensation.",
      body: "Less paperwork for you. Support throughout the whole process.",
      items: [
        {
          title: "Enter your details",
          body: "Flight number, date and the main problem. A few details are enough to get started.",
        },
        {
          title: "We check your case",
          body: "We check the circumstances of the flight. A lawyer determines whether there are grounds for a compensation claim.",
        },
        {
          title: "Claim and payout",
          body: "We run the claim and keep you updated on its status. Once the claim succeeds, the compensation goes to your account.",
        },
      ],
    },
    promo: {
      badge: "CURRENT OFFER",
      titleA: "No costs or commission*",
      titleB: "You keep the full compensation amount.",
      compareOtherLabel: "Other platforms take:",
      compareOtherPct: "30–50%",
      compareUsLabel: "Letkasni.rs:",
      compareUsPct: "0%",
      button: "Check your flight for free",
      note: "* During the promotional period.",
    },
    compensation: {
      aria: "Compensation amounts and quick check",
      amountsTitle: "How much can you get?",
      amountsBody:
        "Compensation depends on the flight distance and the circumstances. It is calculated per passenger and does not depend on the ticket price.",
      amountsButton: "Check your flight",
      tiers: [
        { label: "Up to 1,500 km", amount: "up to €250", example: "e.g. Belgrade – Vienna, Belgrade – Zurich" },
        { label: "1,500–3,500 km", amount: "up to €400", example: "e.g. Belgrade – London, Belgrade – Madrid" },
        { label: "Over 3,500 km", amount: "up to €600", example: "e.g. Belgrade – New York, Belgrade – Chicago" },
      ],
      amountsNote:
        "These are the maximum amounts per passenger. On longer routes and in special circumstances the amount may be reduced, which is why we review every case individually.",
      phoneTitle: "Check your flight",
      phoneBody: "Choose what happened and enter the basic flight details. We take care of the rest.",
      phoneButton: "Start the check",
      phoneAria: "Example of the mobile check: choosing the flight problem",
      phoneBadge: "FREE CHECK",
      phoneQuestion: "What happened to your flight?",
      phoneOptions: ["Flight delayed 3+ hours", "Flight cancelled", "Another issue"],
      phoneNext: "Start the check →",
    },
    benefits: {
      title: "Why do passengers choose Letkasni.rs?",
      body: "Your case deserves someone who understands both the passenger and the local procedures.",
      items: [
        {
          title: "Serbia is our focus",
          body: "We specialise in flights to and from Serbia. We know the local procedures and how claims get resolved.",
        },
        {
          title: "Support in your language",
          body: "You talk to people who know your case. You get clear answers to your questions.",
        },
        {
          title: "Your case in expert hands",
          body: "A lawyer determines whether there are grounds for compensation. We guide you through the steps and the communication with the airline.",
        },
        {
          title: "An easy start",
          body: "The flight number, date and the main problem are enough to begin. We guide you through the check step by step.",
        },
        {
          title: "Less paperwork for you",
          body: "Send the details and documents we need. We take over the communication and run the claim.",
        },
        {
          title: "You know how your case is going",
          body: "We keep you updated on the status of your claim and the next steps. Support is there throughout the process.",
        },
      ],
      button: "Check your flight for free",
      link: "See how it works",
    },
    airlines: {
      badge: "0% commission — you keep the full amount*",
      title: "We handle claims against all major airlines.",
      body: "We take on cases for flights to and from Serbia, regardless of the ticket price.",
      points: ["The Serbian market is our focus", "Local people, direct support", "A lawyer handles your case"],
      button: "Check your compensation",
      note: "* During the promotional period.",
      noteLink: "See the terms of service.",
      listAria: "Airlines",
    },
    quickCheck: {
      titleA: "You keep travelling,",
      titleB: "we handle the paperwork.",
      badge: "FREE CHECK",
      subtitle: "Check your flight",
      body: "Choose what happened and enter the basic flight details. We take care of the rest.",
      points: ["Free check", "0% commission during the promotional period*"],
      button: "Check your flight",
      noteLink: "See the terms of service.",
      imageAlt: "A smiling couple looking at a phone together",
    },
    localSupport: {
      badge: "CONTACT",
      title: "Local team, direct support",
      body: "A delay already takes enough of your time. We write to the airline, track the deadlines and answer rejections, and you get an update at every important step.",
      points: ["You write and talk to us in Serbian or English", "Local team, direct support", "We update you at every important step"],
      contactLead: "Have a question? Get in touch:",
      imageAlt: "A bright office with a desk and plants — illustrative photo",
    },
    testimonials: {
      eyebrow: "PASSENGER REVIEWS",
      titleA: "What our ",
      titleB: "clients say.",
      role: "Passenger",
      outcome: "Compensation per passenger",
      ratingAria: "Rating: 5 out of 5 stars",
      items: [
        {
          name: "Miloš Nikolić",
          route: "Niš – Vienna",
          amount: "€250",
          quote:
            "After my flight was cancelled, I didn't know whom to write to or what to ask for. I called the contact number, Bojana from support explained everything clearly, I sent the documents and that was it.",
        },
        {
          name: "Lazar Miučin",
          route: "Belgrade – London",
          amount: "€400",
          quote: "I was told it was all very professional because it's genuinely run by our people. That's how it was, and 400 EUR landed in my account. :)",
        },
        {
          name: "Nikola Marinić",
          route: "Belgrade – New York",
          amount: "€600",
          quote:
            "We missed our connection because of a delay - a small chaos in life and a million questions about what next. I was immediately referred to a Serbian lawyer who handled everything very professionally. We were paid 2400 EUR for the whole family.",
        },
      ],
    },
    faq: {
      title: "Frequently asked questions",
      items: [
        {
          q: "How much money can I get?",
          a: "Under EU Regulation 261/2004, compensation is usually €250, €400 or €600 per passenger, depending on the flight distance and the circumstances of the delay. The ticket price does not affect the amount.",
        },
        {
          q: "How much does your service cost?",
          a: "The offer with no costs or commission applies during the promotional period. We confirm the terms that apply to your case before the claim starts. If the case goes to court, the lawyer handling your case is paid only by the airline.",
        },
        {
          q: "What do I need for the check?",
          a: "For the first step, the flight number, date and a basic description of the problem are enough. We ask for additional documents after the initial review of the case.",
        },
        {
          q: "What if the airline has already rejected my claim?",
          a: "A rejection does not necessarily mean you have no right to compensation. We carry out our own review of the flight circumstances before deciding on the next steps.",
        },
        {
          q: "How long does the process take?",
          a: "It depends on the airline and the circumstances of the case. Cases that need additional checks or court proceedings can take longer. We keep you regularly updated on the status of your claim.",
        },
        {
          q: "Can I claim compensation for an older flight?",
          a: "It is possible, depending on the flight date and the rules that apply to your case. Send us the flight details so we can check whether the claim can still be submitted.",
        },
      ],
    },
    supportHighlights: {
      title: "We're here for you.",
      body: "For any question about your flight or your case, get in touch — we write and talk to you in Serbian.",
      items: [
        { title: "24/7", body: "You can submit your claim at any time." },
        { title: "Support in Serbian", body: "You write and talk to our team in Serbian." },
        { title: "A lawyer handles your case", body: "A lawyer determines the grounds and handles the airline communication." },
      ],
    },
    cta: {
      badge: "FREE CHECK",
      titleA: "Don't leave your money",
      titleB: "with the airline.",
      body: "Check your flight. We take care of the next steps.",
      button: "Check your flight for free",
      artTitle: "Example flight check: delayed 4 hours and 12 minutes, possible compensation up to 600 euros. The amount depends on the review of the case.",
      artFlightLabel: "YOUR FLIGHT NUMBER",
      artExample: "EXAMPLE CHECK",
      artStatus: "DELAYED · 4 h 12 min",
      artRoute: "BEG → JFK · 14 March",
      artAmountLabel: "Possible compensation",
      artAmount: "up to €600",
      artAmountNote: "We confirm the amount after reviewing the case.",
      artChecks: ["Free check", "Local support", "In Serbian"],
    },
    blog: {
      eyebrow: "TIPS FOR PASSENGERS",
      title: "Latest from the blog.",
      all: "All articles",
      read: "Read the article",
    },
    footer: {
      socialAria: "Social media",
      officeTitle: "Your flight. Our care.",
      officeBody: "Check whether you can claim up to €600 per passenger. We take over the communication and run the claim.",
      officeButton: "Start the check",
      supportEyebrow: "LOCAL SUPPORT",
      brandColumn: "Letkasni.rs",
      brandLinks: [
        { to: "about", label: "About us" },
        { to: "#kako-radi", label: "How it works" },
        { to: "#prednosti", label: "Why Letkasni.rs" },
        { to: "#iskustva", label: "Passenger reviews" },
        { to: "faq", label: "FAQ" },
        { to: "blog", label: "Blog" },
        { to: "contact", label: "Contact" },
      ],
      rightsColumn: "Passenger rights",
      rightsLinks: [
        { guide: "air-passenger-rights", label: "Passenger rights" },
        { guide: "flight-delay-compensation", label: "Flight delay" },
        { guide: "flight-cancellation-compensation", label: "Cancelled flight" },
        { guide: "missed-connection-compensation", label: "Missed connection" },
      ],
      otherColumn: "Other flight problems",
      otherLinks: [
        { guide: "overbooking-compensation", label: "Overbooking" },
        { guide: "denied-boarding-compensation", label: "Denied boarding" },
        { guide: "delayed-baggage-compensation", label: "Delayed baggage" },
        { guide: "airline-strike-compensation", label: "Airline strike" },
      ],
      copyright: "© 2026 Letkasni.rs. All rights reserved.",
      terms: "Terms of use",
      privacy: "Privacy policy",
      emailOffers: "Email offers",
      privacySettings: "Privacy settings",
    },
  },
} as const;

export type LkLocale = keyof typeof copy;
export type LkCopy = (typeof copy)[LkLocale];
